[db]
1000=err.db.connect:数据库连接错误
1001=err.db.userpwd:用户名密码错误
1002=err.db.nonexist.table:表名不存在
1003=err.db.nonexist.col:列名不存在
1004=err.db.col.type:数据类型错误
1005=err.db.sql:sql语句错误

[net]
2000=err.net.http.param:参数错误
2001=err.net.http.timeout:请求超时
2002=err.net.http.request:请求异常
2003=err.net.http.result:请求结果错误
2004=err.net.http.resource.nonexist:请求资源不存在
2005=err.net.http.reject:请求拒绝

2006=err.net.socket.connect:socket连接失败
2007=err.net.socket.connect:

[param]
3000=err.param.notnull:参数不能为空
3001=err.param.format:格式错误
3002=err.param.length:长度错误
3003=err.param.size:大小错误
3004=err.param.type:类型错误


[file]
4000=err.file.read:文件读取错误
4001=err.file.write:文件写错误
4002=err.file.nonexist:文件不存在
4003=err.file.create:文件创建失败
4004=err.file.type:文件类型错误
4006=err.file.size:文件大小错误
4005=err.file.permission:文件操作权限错误

[logic]
5000=err.logic.requestdata.nonexist:请求的数据不存在
5001=err.logic.savedata.crash:保存数据失败数据冲突
5002=err.logic.deletedata.related:删除数据失败数据有关联
5003=err.logic.deletedata.nonexist:删除数据失败删除的对象不存在


