package cola.machine.bean;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.name
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.prop
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private String prop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.type
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.pid
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private String pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.id
     *
     * @return the value of t_resource.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.id
     *
     * @param id the value for t_resource.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.name
     *
     * @return the value of t_resource.name
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.name
     *
     * @param name the value for t_resource.name
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.prop
     *
     * @return the value of t_resource.prop
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public String getProp() {
        return prop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.prop
     *
     * @param prop the value for t_resource.prop
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setProp(String prop) {
        this.prop = prop == null ? null : prop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.type
     *
     * @return the value of t_resource.type
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.type
     *
     * @param type the value for t_resource.type
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.pid
     *
     * @return the value of t_resource.pid
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.pid
     *
     * @param pid the value for t_resource.pid
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }
}